typography_spectrum: 0.2840118769018699
color:
  brandStrength: 0.7801177835822253
  lightness: 0.5258790373910993
  saturation: 0.002046292246605205
  rhythmicContrast: 0.16517448086964687
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
github: true
layout_spectrum: 0.5725904357945085
author:
  name: JacknBella
  email: JB@idcsg.com
  url: 'http://jacknbella.website'
name: Jack & Bella
url: 'http://jacknbella.website'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: The Beginning
    id: c2ca4e02-edee-4afb-8738-2bfdb9b427b7
    type: content
favicon: null
title: Jack&Bella
content: []
description: Bad Bunny Chronicles
purpose:
  - type: contact
    url: 'mailto:jB@idcsg.com'
    label: Contact
